config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#about'
  
  resources :posts do
    resources :comments
  end
  
  get '/about' => 'pages#about'
  
  devise_for :users, controllers: { sessions: 'users/sessions' }
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  validates :title, presence: true, length: { minimum: 3 }
  validates :body,  presence: true
  has_many :comments, dependent: :destroy
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!, except: [:index, :show]
    
  def index
    @post = Post.all.order('created_at DESC')
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if
      @post.save
      flash[:success] = "Post Created!"
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Post Updated!"
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:danger] = "Post deleted!"
    redirect_to root_path
  end
  
  
  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
  
  <%= render 'shared/form' %>
  
</div>

app/views/posts/index.html.erb
<% @post.each do |p| %>
  <div class="post_wrapper">
    <h2 class="title">
      <%= link_to p.title, p %>
      <p class="date">
      <%= p.created_at.strftime("%B %-d, %Y") %>
      </p>
    </h2>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>
  
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
    <div id="errors">
      <h2>Your post contains <%= pluralize(@post.errors.count, "error") %>.</h2>
      <ul>
        <% @post.errors.full_messages.each do |m| %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    
    <p>
      <%= f.submit %>
    </p>
    
  <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>
  
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago.
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post) %>
      | <%= link_to 'Delete', post_path(@post), method: :delete,
                              data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  
  <p class="body">
    <%= @post.body %>
  </p>
  
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render partial: 'shared/comment', collection: @post.comments, as: :comment %>
    
    <h3>Add a comment:</h3>
    <%= render 'shared/comment_form' %>
    
  </div>
</div>