config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#about'
  
  resources :posts do
    resources :comments
  end
  
  get '/about' => 'pages#about'
  
  devise_for :users, controllers: { sessions: 'users/sessions' }
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>John Lander</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
      <%= image_tag "logo.jpg" %>
      <% end %>
    </div>
    
    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", posts_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
    
    <ul>
      <li class="category">Social</li>
      <li><a href="https://twitter.com/JohnWLIV">Twitter</a></li>
      <li><a href="https://www.linkedin.com/profile/view?id=AAMAAAIISjEBQSfQ3So12f6s7HgpqxPdaN96Gy4">LinkedIn</a></li>
      <li><a href="http://stackoverflow.com/users/2715792/johnwliv">StackOverflow</a></li>
      <li><a href="https://github.com/JohnWL">Github</a></li>
    </ul>
    
    <ul>
      <li class="category">Rails Apps</li>
      <li><a href="http://showandtell.johnlander.me">Show and Tell</a></li>
      <li><a href="http://forum.johnlander.me">Message Forum</a></li>
      <li><a href="http://jobs.johnlander.me">Job Listings</a></li>
      <li><a href="http://movies.johnlander.me">Movie Reviews</a></li>
      <li><a href="http://notepad.johnlander.me">Personal Notepad</a></li>
      <li><a href="http://pinterest.johnlander.me">Pinterest Style App</a></li>
      <li><a href="http://recipes.johnlander.me">Food Recipes</a></li>
      <li><a href="http://reddit.johnlander.me">Reddit Style App</a></li>
      <li><a href="http://todo.johnlander.me">Todo List</a></li>
      <li><a href="http://wiki.johnlander.me">Wiki</a></li>
      <li><a href="http://exercise.johnlander.me">Exercise Log</a></li>
    </ul>
    
    <% if !user_signed_in? %>
    <ul>
      <li class="category">Admin</li>
      <li><%= link_to 'Admin Login', new_user_session_path %></li>
    </ul>
    <% end %>
  </div>
  
  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
        <p>Home</p>
      <% elsif current_page?(about_path) %>
        <p>About</p>
      <% else %>
        <%= link_to "Back to Home", root_path %>
      <% end %>
      
      <% if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
          <button class="button"><%= link_to "Log Out",
                                     destroy_user_session_path,
                                     method: :delete %></button>
        </div>
      <% end %>
    </div>
    
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    
    <%= yield %>
    
  </div>

</body>
</html>